<a href="https://colab.research.google.com/github/yashikasinha/ML/blob/master/Metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.ones((3, 3), dtype = int)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
import numpy as np
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
import numpy as np
np.empty((2, 4))

array([[2.5748425e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [6]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
